# Generated by Django 4.2.17 on 2025-01-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['sort_index', 'name'], 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='categories',
            name='sort_index',
            field=models.IntegerField(default=100, verbose_name='Порядок сортировки'),
        ),
    ]
